# Generated by Django 2.0.2 on 2018-02-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ciudades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=60)),
                ('last_name', models.CharField(blank=True, max_length=60)),
                ('us_imageine', models.ImageField(default='defaultXfull.png', upload_to='make_upload_path')),
                ('us_birthday', models.DateTimeField()),
                ('us_isactive', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=15, unique=True)),
                ('password', models.CharField(blank=True, max_length=150)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('email', models.EmailField(default='mail@co.co', max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('us_ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ciudades.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype_name', models.CharField(max_length=50)),
                ('usertype_desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
