# Generated by Django 2.0.2 on 2018-02-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='us_birthday',
            field=models.DateField(),
        ),
    ]
