# Generated by Django 2.0.2 on 2018-02-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180213_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='us_isactive',
            field=models.BooleanField(default=False),
        ),
    ]
