# Generated by Django 2.0.2 on 2018-02-14 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180214_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='us_ciudad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ciudades.Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
